### PR TITLE
Add text for graduates and change degree_award to Ptychion.

### PR DESCRIPTION
**Pull request by chris-asl**
Added text for graduates, as reported in official document. The output can be set using the `graduated` flag in `details.tex`. 
To control the output, I've used `\newif\ifgraduated`, as described [here](http://tex.stackexchange.com/questions/5894/latex-conditional-expression). 

Additionally, changed `acadyear`, since in the official document for a graduate, these headers are changed to `1st Semester, 2nd Semester, ..`, where all courses for each semester are listed under their respective semester and the period in which each one was passed, appears in the 5th column. 

Does it look good? Or should I change sth?

### CODE REVIEW

**Review by errikos — CHANGES_REQUESTED** [review]
Hello, thanks for the contribution. Just two things I noticed:
1. In file digrades.cls:184, I think the word "equivalent" does not stick well. Can you provide the Greek version of the sentence?
2. In file digrades.cls:199, I would suggest writing "demostrates if the course..." as "indicates whether the course...".

What do you think? Regards.

**Comment by chris-asl** [comment]
Hello, 

I totally agree with (2) (will change it in a follow-up commit, once we sort-out (1) ).

Regarding (1), the Greek version of this sentence is: "Ο ανωτέρω κατά τη φοίτησή του στο Τμήμα, έχει διδαχθεί τα παρακάτω μαθήματα με τις διδακτικές μονάδες που έχει το καθένα και έλαβε την αντίστοιχη βαθμολογία." 
How should we translate this?

**Comment by errikos** [comment]
Maybe the word "corresponding" would be more appropriate. Like this:

> _The aforementioned student during his undergraduate studies in the Department, has been taught all the **courses listed** below, with their respective credits and has received the **corresponding** grades._

Changes I have made in the sentence appear in bold.

Let me know what you think. Regards.

**Comment by chris-asl** [comment]
LGTM :-)
I integrated these changes and pushed the new commit. 
Let me know if that's ok.

**Comment by errikos** [comment]
Merged. Thanks for your contribution!

**Pull request merged**
